# -*- coding: utf-8 -*-
"""SupplyChainAnalysisProj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17C9-xT5G1Wenxt71zFp82cWZ5DpD1h51
"""

import pandas as pd
import numpy as np

fi=pd.read_csv("/content/supply_chain_data.csv")
print(fi)

print(fi.shape,'\n')
fi.columns

#Feature Engineering / Business math
fi['Avg_Daily_Sales']=fi['Number of products sold']/30
#assumed no.of products sold occurred over a 30 day period to calculate the daily sales

fi['Safety_Stock']=(fi['Avg_Daily_Sales']*fi['Lead times'])*0.20
#calculating safety stock
#set a standard safety buffer of 20% of the standard lead time demand

fi['Reorder_Point']=(fi['Avg_Daily_Sales']*fi['Lead times'])+fi['Safety_Stock']
#Thus is the exact inventory level at which the system should trigger a new purchase order

fi['Reorder_Point']=np.ceil(fi['Reorder_Point'])
fi['Safety_Stock']=np.ceil(fi['Safety_Stock'])
#rounded the nums up

#Risk Flagging
def check_inventory_status(row):
  if row['Stock levels'] <= 0:
    return "OUT OF STOCK!!!"
  elif row['Stock levels'] <= row['Reorder_Point']:
    return "REORDER IMMEDIATELY!!"
  elif row['Stock levels'] <= (row['Reorder_Point']*1.5):
    return "LOW STOCK WARNING!"
  else:
    return "HEALTHY INVENTORY"
#wrote a logical function to compare current stock against the Reorder_Point

fi['Inventory_Status']=fi.apply(check_inventory_status, axis=1)
#apply the function to create a new status column

#keeping only the columns the business actually needs for the Power BI dashboard
columns_to_keep =['SKU','Product type','Price','Stock levels','Lead times','Avg_Daily_Sales','Reorder_Point','Inventory_Status']
final_fi=fi[columns_to_keep]

final_fi.to_csv("inventory4bi.csv", index=False)
print("Success!! Inventory Optimization complete. File Ready for Power BI")